se agrego drawer.Navigator en frontend
BautistaDalmasso/Skynet-LCDS-2024 pull request #12
Opened 2024-03-28 21:10 UTC by paulinAPQ

2024-03-29 16:39 UTC, MaxiDeMichieli requested changes

2024-03-29 16:39 UTC, MaxiDeMichieli commented on Frontend/src/components/Form.tsx
> +const [nombre, set_nombre]= useState("")
Intentemos escribir todo el código en inglés para ser consistentes y no tenerlo en inglés y español

2024-03-29 16:39 UTC, MaxiDeMichieli commented on Frontend/App.tsx
> +       <Drawer.Screen name="Perfil" component={Perfil} />
Crea una nueva ruta en el enum `Routes` en vez de poner directamente el string "Perfil"

2024-03-29 16:39 UTC, MaxiDeMichieli commented on Frontend/App.tsx
> +          name={"Registrarse"}
Lo mismo del enum `Routes`

2024-03-29 16:39 UTC, MaxiDeMichieli commented on Frontend/src/components/ChatHeader.tsx
> +      <TouchableOpacity onPress={() =>  navigation.navigate("Home")}>
Usa `Routes.Home` en vez del string directamente

2024-03-29 16:39 UTC, MaxiDeMichieli commented on Frontend/src/components/Form.tsx
> +//const [se_registro, set_se_registro] = useState(false);
Si no se va a usar borremoslo

2024-03-29 16:39 UTC, MaxiDeMichieli commented on Frontend/src/components/Form.tsx
> +//
Borra este comentario que no se usa

2024-03-29 16:39 UTC, MaxiDeMichieli commented on Frontend/App.tsx
> +import Perfil from "./src/components/Perfil";
Ponele el nombre en inglés al componente asi mantenemos un mismo idioma para todo el código

2024-03-29 20:22 UTC, MaxiDeMichieli commented on Frontend/src/components/Form.tsx
> +const [nombre, set_nombre]= useState("")
Tambien usemos camel case como en todo el resto del código

2024-03-30 14:28 UTC, BautistaDalmasso approved these changes
Creo que están todos los cambios sugeridos por Maxi.

2024-03-30 14:51 UTC, MaxiDeMichieli approved these changes

2024-03-31 14:02 UTC, merged