add show loans offline
BautistaDalmasso/Skynet-LCDS-2024 pull request #59
Opened 2024-05-07 19:02 UTC by jzm-n

2024-05-07 23:28 UTC, MaxiDeMichieli requested changes, later dismissed

2024-05-07 23:28 UTC, MaxiDeMichieli commented on Frontend/src/components/BookList.tsx
> +      handleJSON({
Siempre va a guardar solo un préstamo? Yo lo guardaría como un array en el storage

2024-05-07 23:28 UTC, MaxiDeMichieli commented on Frontend/src/components/BookList.tsx
> +      await AsyncStorage.setItem("requestData", jsonData);
Al item que guardamos en el storage le pondría un nombre mas representativo, porque después podemos guardar más cosas. Le podemos poner `loans`. También lo guardaría en un Enum para poder usarlo después en donde obtenemos el valor del storage. El enum podría ser algo así:
`enum StorageKeys {
    LOANS = 'loans'
}`

2024-05-07 23:28 UTC, MaxiDeMichieli commented on Frontend/src/components/ShowLoans.tsx
> +        const jsonData = await AsyncStorage.getItem("requestData");
Acá podrías usar el enum que te comenté en el otro archivo

2024-05-08 20:05 UTC, BautistaDalmasso approved these changes

2024-05-09 14:48 UTC, merged